specVersion: 1.0.0
name: juno-dictionary
version: 1.0.0
runner:
  node:
    name: '@subql/node-cosmos'
    version: "*"
  query:
    name: '@subql/query'
    version: "*"
description: A SubQuery project provide dictionary data & service for the Terra network
schema:
  file: ./schema.graphql
network:
  chainId: juno-1
  endpoint: https://rpc.juno-1.beta.api.onfinality.io/

dataSources:
  - kind: cosmos/Runtime
    startBlock: 3062001
    chainTypes: # This is a beta feature that allows support for any Cosmos chain by importing the correct protobuf messages
      cosmos.slashing.v1beta1:
        file: "./proto/cosmos/slashing/v1beta1/tx.proto"
        messages:
          - "MsgUnjail"
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: cosmos/EventHandler
        - handler: handleMessage
          kind: cosmos/MessageHandler
