specVersion: 0.3.0
description: A subquery project provide dictionary data & service for a substrate-based network
repository: 'https://github.com/subquery/subql-dictionary'
schema: 
  file: ./schema.graphql
network:
  endpoint: 'https://bombay.stakesystems.io'
  chainId: 'bombay-12'
dataSources:
  - name: main
    kind: terra/Runtime
    startBlock: 5900001
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: terra/EventHandler