specVersion: 1.0.0
name: juno-dictionary
version: 1.0.0
runner:
  node:
    name: '@subql/node-cosmos'
    version: "latest"
  query:
    name: '@subql/query'
    version: "latest"
description: A SubQuery project provide dictionary data & service for the Terra network
schema:
  file: ./schema.graphql
network:
  chainId: juno-1
  endpoint: https://rpc-juno.itastakers.com/

dataSources:
  - kind: cosmos/Runtime
    startBlock: 3168000
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: cosmos/EventHandler
        - handler: handleMessage
          kind: cosmos/MessageHandler
