specVersion: 0.3.0
description: A SubQuery project provide dictionary data & service for the Terra network
repository: 'https://github.com/subquery/terra-dictionary'
schema: 
  file: ./schema.graphql
network:
  endpoint: 'https://terra-columbus-5.beta.api.onfinality.io'
  chainId: 'columbus-5'
dataSources:
  - name: main
    kind: terra/Runtime
    startBlock: 6745053
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: terra/EventHandler
        - handler: handleMessage
          kind: terra/MessageHandler
